"""initial DB

Revision ID: fb4d57f652d8
Revises: 
Create Date: 2020-01-13 18:26:01.015599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb4d57f652d8'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('browsersession',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('browser_session', sa.Text(), nullable=True),
    sa.Column('create_session', sa.DateTime(), nullable=True),
    sa.Column('page', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_browsersession'))
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('browsersession')
    # ### end Alembic commands ###
